[package]
name = "gauche"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
name = "queries"
harness = false

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
